
package com.club.sms.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SMSMasivosAPISoap", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SMSMasivosAPISoap {


    /**
     * 
     * @param texto
     * @param clave
     * @param numero
     * @param test
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EnviarSMS", action = "http://servicio.smsmasivos.com.ar/ws/EnviarSMS")
    @WebResult(name = "EnviarSMSResult", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/")
    @RequestWrapper(localName = "EnviarSMS", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/", className = "pruebawsdl.EnviarSMS")
    @ResponseWrapper(localName = "EnviarSMSResponse", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/", className = "pruebawsdl.EnviarSMSResponse")
    public String enviarSMS(
        @WebParam(name = "usuario", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/")
        String usuario,
        @WebParam(name = "clave", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/")
        String clave,
        @WebParam(name = "numero", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/")
        long numero,
        @WebParam(name = "texto", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/")
        String texto,
        @WebParam(name = "test", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/")
        boolean test);
        
    
    /**
     * 
     * @param clave
     * @param solonoleidos
     * @param usuario
     * @param origen
     * @param marcarcomoleidos
     * @return
     *     returns pruebawsdl.ArrayOfClsRespuesta
     */
    @WebMethod(operationName = "RecibirSMS", action = "http://servicio.smsmasivos.com.ar/ws/RecibirSMS")
    @WebResult(name = "RecibirSMSResult", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/")
    @RequestWrapper(localName = "RecibirSMS", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/", className = "pruebawsdl.RecibirSMS")
    @ResponseWrapper(localName = "RecibirSMSResponse", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/", className = "pruebawsdl.RecibirSMSResponse")
    public ArrayOfClsRespuesta recibirSMS(
        @WebParam(name = "usuario", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/")
        String usuario,
        @WebParam(name = "clave", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/")
        String clave,
        @WebParam(name = "origen", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/")
        String origen,
        @WebParam(name = "solonoleidos", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/")
        boolean solonoleidos,
        @WebParam(name = "marcarcomoleidos", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/")
        boolean marcarcomoleidos);

}
