
package smsmasivos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SMSMasivosAPIHttpPost", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SMSMasivosAPIHttpPost {


    /**
     * 
     * @param texto
     * @param clave
     * @param numero
     * @param test
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EnviarSMS")
    @WebResult(name = "string", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/", partName = "Body")
    public String enviarSMS(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "usuario")
        String usuario,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "clave")
        String clave,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "numero")
        String numero,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "texto")
        String texto,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "test")
        String test);

    /**
     * 
     * @param clave
     * @param solonoleidos
     * @param usuario
     * @param origen
     * @param marcarcomoleidos
     * @return
     *     returns javaapplication9.ArrayOfClsRespuesta
     */
    @WebMethod(operationName = "RecibirSMS")
    @WebResult(name = "ArrayOfClsRespuesta", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/", partName = "Body")
    public ArrayOfClsRespuesta recibirSMS(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "usuario")
        String usuario,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "clave")
        String clave,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "origen")
        String origen,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "solonoleidos")
        String solonoleidos,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "marcarcomoleidos")
        String marcarcomoleidos);

}
