
package smsmasivos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SMSMasivosAPI", targetNamespace = "http://servicio.smsmasivos.com.ar/ws/", wsdlLocation = "http://servicio.smsmasivos.com.ar/ws/SMSMasivosAPI.asmx?WSDL")
public class SMSMasivosAPI
    extends Service
{

    private final static URL SMSMASIVOSAPI_WSDL_LOCATION;
    private final static WebServiceException SMSMASIVOSAPI_EXCEPTION;
    private final static QName SMSMASIVOSAPI_QNAME = new QName("http://servicio.smsmasivos.com.ar/ws/", "SMSMasivosAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://servicio.smsmasivos.com.ar/ws/SMSMasivosAPI.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMSMASIVOSAPI_WSDL_LOCATION = url;
        SMSMASIVOSAPI_EXCEPTION = e;
    }

    public SMSMasivosAPI() {
        super(__getWsdlLocation(), SMSMASIVOSAPI_QNAME);
    }

    public SMSMasivosAPI(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMSMASIVOSAPI_QNAME, features);
    }

    public SMSMasivosAPI(URL wsdlLocation) {
        super(wsdlLocation, SMSMASIVOSAPI_QNAME);
    }

    public SMSMasivosAPI(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMSMASIVOSAPI_QNAME, features);
    }

    public SMSMasivosAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SMSMasivosAPI(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SMSMasivosAPISoap
     */
    @WebEndpoint(name = "SMSMasivosAPISoap")
    public SMSMasivosAPISoap getSMSMasivosAPISoap() {
        return super.getPort(new QName("http://servicio.smsmasivos.com.ar/ws/", "SMSMasivosAPISoap"), SMSMasivosAPISoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SMSMasivosAPISoap
     */
    @WebEndpoint(name = "SMSMasivosAPISoap")
    public SMSMasivosAPISoap getSMSMasivosAPISoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.smsmasivos.com.ar/ws/", "SMSMasivosAPISoap"), SMSMasivosAPISoap.class, features);
    }

    /**
     * 
     * @return
     *     returns SMSMasivosAPISoap
     */
    @WebEndpoint(name = "SMSMasivosAPISoap12")
    public SMSMasivosAPISoap getSMSMasivosAPISoap12() {
        return super.getPort(new QName("http://servicio.smsmasivos.com.ar/ws/", "SMSMasivosAPISoap12"), SMSMasivosAPISoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SMSMasivosAPISoap
     */
    @WebEndpoint(name = "SMSMasivosAPISoap12")
    public SMSMasivosAPISoap getSMSMasivosAPISoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.smsmasivos.com.ar/ws/", "SMSMasivosAPISoap12"), SMSMasivosAPISoap.class, features);
    }

    /**
     * 
     * @return
     *     returns SMSMasivosAPIHttpGet
     */
    @WebEndpoint(name = "SMSMasivosAPIHttpGet")
    public SMSMasivosAPIHttpGet getSMSMasivosAPIHttpGet() {
        return super.getPort(new QName("http://servicio.smsmasivos.com.ar/ws/", "SMSMasivosAPIHttpGet"), SMSMasivosAPIHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SMSMasivosAPIHttpGet
     */
    @WebEndpoint(name = "SMSMasivosAPIHttpGet")
    public SMSMasivosAPIHttpGet getSMSMasivosAPIHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.smsmasivos.com.ar/ws/", "SMSMasivosAPIHttpGet"), SMSMasivosAPIHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns SMSMasivosAPIHttpPost
     */
    @WebEndpoint(name = "SMSMasivosAPIHttpPost")
    public SMSMasivosAPIHttpPost getSMSMasivosAPIHttpPost() {
        return super.getPort(new QName("http://servicio.smsmasivos.com.ar/ws/", "SMSMasivosAPIHttpPost"), SMSMasivosAPIHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SMSMasivosAPIHttpPost
     */
    @WebEndpoint(name = "SMSMasivosAPIHttpPost")
    public SMSMasivosAPIHttpPost getSMSMasivosAPIHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.smsmasivos.com.ar/ws/", "SMSMasivosAPIHttpPost"), SMSMasivosAPIHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMSMASIVOSAPI_EXCEPTION!= null) {
            throw SMSMASIVOSAPI_EXCEPTION;
        }
        return SMSMASIVOSAPI_WSDL_LOCATION;
    }

}
